config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'

  get 'relationships/destroy'

  get 'vehicles/index'

  get 'vehicles/new'

resources :smugglers do
  resources :relationships
end

resources :tycoons
resources :missions
resources :vehicles

  root 'sessions#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create_smuggler_session',  as: :login_smuggler
  delete 'logout' => 'sessions#destroy_session', as: :logout
  post 'login_tycoon' => 'sessions#create_tycoon_session', as: :login_tycoon

  post '/smuggler/:smuggler_id/' => 'relationships#create'
  delete '/smuggler/:smuggler_id' => 'relationships#destroy'
  

end

app/models/smuggler.rb
class Smuggler < ActiveRecord::Base
	has_many :vehicles, through: :missions
	has_many :missions

	has_secure_password
	validates_presence_of :password, on: :create
	validates_presence_of :username, on: :create
	validates_presence_of :email, on: :create
	validates_uniqueness_of  :email
	validates_uniqueness_of :username


	has_many :active_relationships, class_name: "Relationship",
	foreign_key: "follower_id",
	dependent: :destroy
	has_many :passive_relationships, class_name: "Relationship",
	foreign_key: "followed_id",
	dependent: :destroy
	has_many :following, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships, source: :follower


	def follow!(other_smuggler)
		active_relationships.create(followed_id: other_smuggler.id)
	end

	def unfollow!(other_smuggler)
		active_relationships.find_by(followed_id: other_smuggler.id).destroy
	end

	def following?(other_smuggler)
		following.include?(other_smuggler)
	end


	#Paperclip below 
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/controllers/smugglers_controller.rb
class SmugglersController < ApplicationController
 
  def index
  		@smugglers = Smuggler.all
      @tycoons = Tycoon.all
      # Sets the Tycoons and the smugglers to be viewed on the smuggler index page.
  end

  def show
      # Finds the smuggler page and makes sure to display the information of the corresponding smuggler.
  		@smuggler = Smuggler.find(params[:id])
      current_smuggler = @current_smuggler
  end

  def new
  		@smuggler = Smuggler.new
  end

  def create
      # passes the strong smuggler params through a new smuggler.
	  	@smuggler = Smuggler.new(smuggler_params)
		  	if @smuggler.save
		  		redirect_to login_path
		  		flash[:notice] = "Your account was created."
          # if smuggler is saved it will redirect to the login and alert that it was created.
		  	else
		  		redirect_to :back
		  		flash[:notice] = "Something went wrong."
          # If not the user is alerted and redirected back.
		  	end
  end

  def edit
    @smuggler = Smuggler.find(params[:id])
    # Sets the smuggler variable to the correct smuggler for the page.
  end

  def update
    @smuggler = Smuggler.find(params[:id])
    if logged_in_ty?
        @smuggler.update(smuggler_params)
        # updates smuggler with strong params.
        redirect_to smuggler_path @smuggler
        # rredirects to the smuggler's show page. and alert them.
        flash[:notice] = "Smuggler Updated!"
    elsif logged_in?
      # If there is a current smuggler continue
      if current_smuggler.id == @smuggler.id
        # If the currentSmugglers id matches the smuggler for this page continue 
          @smuggler.update(smuggler_params)
          # updates smuggler with strong params.
          redirect_to smuggler_path @smuggler
          # rredirects to the smuggler's show page. and alert them.
      else
          # if current_smugglers id does not match redirects back and alerts user.
          redirect_to :back
          flash[:notice] = "Not your account to update."  
        end
    else
      # if not logged in
      redirect_to :back
      flash[:notice] = "You do not have permission to update."
    end
  end

  def destroy
    # This action has very similar logic to the update function. Checks if there is a logged in tycoon or if logged in
    # smuggler has a matching id. If either of those account is deleted and smuggler logged out. Else redirect back.
    @smuggler = Smuggler.find(params[:id])
    if logged_in_ty? 
      @smuggler.destroy
      redirect_to smugglers_path
      flash[:notice] = "Account Deleted."
    elsif logged_in?
        if @current_smuggler.id == @smuggler.id
          	@smuggler.destroy
            session[:smuggler_id] = nil
            redirect_to smugglers_path
            flash[:notice] = "Account Deleted."
        else
            redirect_to :back
            flash[:notice] = "Not your account to delete."  
        end
    else
      redirect_to :back
      flash[:notice] = "You do not have permission to delete this account."  
    end
  end

layout "smug"
# All actions and views related to smugglers use the smug layout.
  private
  
  def smuggler_params

		params.require(:smuggler).permit(:username, :email, :password, :location, :home, :avatar)

  end

end

app/helpers/smugglers_helper.rb
module SmugglersHelper
end

app/views/smugglers/edit.html.erb
			<h1>Update your Profile</h1>
			<%= form_for @smuggler do |f| %>
			<%= f.label :username %>
			<%= f.text_field :username %>
			<%= f.label :email %>
			<%= f.text_field :email %>
			<%= f.label :avatar %>
			<%= f.file_field :avatar %>
			<%= f.submit :update %>
			<% end %>

app/views/smugglers/index.html.erb
<div class = "user_content">
	<div class="smug_index">
		<h3>The Smugglers</h3>
			<% @smugglers.each do |smuggler| %>
				<%= link_to(image_tag(smuggler.avatar.url(:thumb)), smuggler_path(smuggler.id), method: :get, class: 'avatar') %>
				<%= link_to smuggler.username, smuggler_path(smuggler.id), method: :get, class: 'smuggler_name' %>
				<div class = "follow_button_div">
					<% if logged_in? %>
						<% if current_smuggler.following?(smuggler) %>
							<%= button_to "unfollow", smuggler_relationship_path(smuggler.id, current_smuggler.id), method: :delete, remote: :true, class: "follow_button" %>
						<% else %>
							<%= button_to "Follow", smuggler_relationships_path(smuggler.id, current_smuggler.id), method: :post,  remote: true, class: "follow_button" %>
						<% end %>
					<% end %>
				</div>	
				<br><br>
			<% end %>
		<h3>The Tycoons</h3>
		<% @tycoons.each do |t| %>
			<%= link_to(image_tag(t.avatar.url(:thumb)), tycoon_path(t.id), method: :get, class: 'avatar') %>
			<%= link_to t.username, tycoon_path(t.id), method: :get,  class: 'smuggler_name' %>
			<br>
		<% end %>
	</div>
</div>

app/views/smugglers/new.html.erb
<%= form_for @smuggler, :html => { :multipart => true }   do |f| %>
<%= f.label :email %>
<%= f.email_field :email %>
<br>
<%= f.label :username %>
<%= f.text_field :username %>
<br>
<%= f.label :password %>
<%= f.password_field :password %>
<br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<br>
<%= f.label :avatar %>
<%= f.file_field :avatar %>
<br>
<%= f.submit :create %>
<% end %>

app/views/smugglers/show.html.erb
<%= content_tag :p, "Alias: #{@smuggler.username }" %>
<%= @smuggler.username %>
<h4>Mugshot:</h4>
<%= image_tag @smuggler.avatar.url(:medium) %>
<br>
<% if logged_in_ty? %>
	<%= link_to "Delete Smuggler", smuggler_path(@smuggler), method: :delete, class: "smuggler_name" %>
	<br>
	<%= link_to "Update Smuggler", edit_smuggler_path(@smuggler), method: :get, class: "smuggler_name" %>
<% elsif logged_in? %>
	<% current_smuggler.id == @smuggler.id %>
		<%= link_to "Delete Smuggler", smuggler_path(@smuggler), method: :delete, class: "smuggler_name" %>
		<br>
		<%= link_to "Update Smuggler", edit_smuggler_path(@smuggler), method: :get, class: "smuggler_name" %>
<% end %>
<h3>Missions And Vehicles</h3>
<% @smuggler.missions.each do |mission| %>
<%= link_to "Mission: #{mission.name}", mission_path(mission.id), method: :get, class: "smuggler_name" %> 
<br>
<%= content_tag :p, "Cost: $#{mission.cost} usd" %> 
<br>
<%= link_to mission.vehicle.name, vehicle_path(mission.vehicle.id), method: :get, class: "smuggler_name" %>
<br>
<%= image_tag mission.vehicle.image(:thumb) %>
<br><br>
<% end %>