config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'

  get 'relationships/destroy'

  get 'vehicles/index'

  get 'vehicles/new'

resources :smugglers do
  resources :relationships
end

resources :tycoons
resources :missions
resources :vehicles

  root 'sessions#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create_smuggler_session',  as: :login_smuggler
  delete 'logout' => 'sessions#destroy_session', as: :logout
  post 'login_tycoon' => 'sessions#create_tycoon_session', as: :login_tycoon

  post '/smuggler/:smuggler_id/' => 'relationships#create'
  delete '/smuggler/:smuggler_id' => 'relationships#destroy'
  

end

app/models/tycoon.rb
class Tycoon < ActiveRecord::Base
	has_many :vehicles
	has_secure_password


	# paperclip below
  	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/tycoon_controller.rb
raclass TycoonController < ApplicationController
	def index

	end

	def new
		@tycoon = Tycoon.new
	end

	def create
		@tycoon = Tycoon.new(tycoon_params)
		if @tycoon.save
			redirect_to :back
			flash[:notice] = "New Tycoon Created!"
		else
			redirect_to :back
			flash[:notice] = "We could not create your Tycoon. Please try again."
		end
	end

	def update

	end

	def destroy
		if 
		@tycoon = Tycoon.find(params[:id])
		@tycoon.destroy
		redirect_to :back
		flash[:notice] = "Your FatCat was destroyed..."
	end

	private


	def tycoon_params

		params.require(:tycoon).permit(:username, :email, :password, :home, :cigar, :networth)
	end
end

app/controllers/tycoons_controller.rb
class TycoonsController < ApplicationController
	# Currently Tycoons must be created through the rails console. This is for security reasons since Tycoons have a lot of CRUD power.
	 
	def index
		@tycoons = Tycoon.all
		# make the variable equal to all tycoons to display on index.
	end

	def show
		@tycoon = Tycoon.find(params[:id])
		# make variable equal to the corresponding tycoon's page.
	end

	def new
		@tycoon = Tycoon.new
		# variable for creating a new tycoon
	end

	def create
		# passing a new tycoon the tycoon strong params.
		@tycoon = Tycoon.new(tycoon_params)
		if @tycoon.save
			redirect_to :back
			flash[:notice] = "New Tycoon Created!"
		else
			redirect_to :back
			flash[:notice] = "We could not create your Tycoon. Please try again."
		end
	end

	def edit
    @tycoon = Tycoon.find(params[:id])

  	end

  def update
    @tycoon = Tycoon.find(params[:id])
    if logged_in_ty?
      @tycoon.update(tycoon_params)
      redirect_to tycoon_path @tycoon
      flash[:notice] = "Tycoon Updated!"
    else
      redirect_to :back
      flash[:notice] = "Not your profile to edit."
    end
  end

	def destroy 
			@tycoon = Tycoon.find(params[:id])
			@tycoon.destroy
			redirect_to :back
			flash[:notice] = "Your FatCat was destroyed..."
	end

	private


	def tycoon_params

		params.require(:tycoon).permit(:username, :email, :password, :home, :cigar, :networth, :avatar)
	end
end

app/helpers/tycoon_helper.rb
module TycoonHelper
end

app/views/tycoons/edit.html.erb
			<h1>Update your Profile</h1>
			<%= form_for @tycoon do |f| %>
			<%= f.label :username %>
			<%= f.text_field :username %>
			<%= f.label :email %>
			<%= f.text_field :email %>
			<%= f.label :cigar %>
			<%= f.text_field :cigar %>

			<%= f.label :avatar %>
			<%= f.file_field :avatar %>
			<%= f.submit :update %>
			<% end %>

app/views/tycoons/index.html.erb
<h1>All Tycoons</h1>
<% @tycoons.each do |t| %>
	<%= link_to t.username, tycoon_path(t.id), method: :get %>
	<%= image_tag @tycoon.avatar.url(:thumb)  %>
	
	<% end %>
	

app/views/tycoons/show.html.erb
<%=content_tag :h2, "#{@tycoon.username}" %>
<br>
<%= image_tag @tycoon.avatar.url(:medium) %>
<br>
<%= @tycoon.cigar %>
<br>
<%= @tycoon.networth %>

<h2>Tycoons Vehicles</h2>
<% @tycoon.vehicles.each do |v| %>
<%= link_to v.name, vehicle_path(v.id), method: :get, class: "smuggler_name" %>
<br>
<%= image_tag v.image.url(:medium) %>
<br>
<% end %>
<br>
<%= link_to "Update Tycoon", edit_tycoon_path(@tycoon), method: :get %>