config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'

  get 'relationships/destroy'

  get 'vehicles/index'

  get 'vehicles/new'

resources :smugglers do
  resources :relationships
end

resources :tycoons
resources :missions
resources :vehicles

  root 'sessions#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create_smuggler_session',  as: :login_smuggler
  delete 'logout' => 'sessions#destroy_session', as: :logout
  post 'login_tycoon' => 'sessions#create_tycoon_session', as: :login_tycoon

  post '/smuggler/:smuggler_id/' => 'relationships#create'
  delete '/smuggler/:smuggler_id' => 'relationships#destroy'
  

end

app/models/mission.rb
class Mission < ActiveRecord::Base
	belongs_to :smuggler
	belongs_to :vehicle
	validates_presence_of :cargo
	validates :cargo, length: {minimum: 50}
	validates_presence_of :cost
	validates_uniqueness_of :name
	validates :cost, numericality: {greater_than: 999} 
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
	
	def index
		@missions = Mission.all
		# This will set the variable to all missions
	end

	def new
		@mission = Mission.new
		@vehicles = Vehicle.all
		@smugglers = Smuggler.all
		# Sets the mission variable to a new mission. The vehicle and smuggler are defined as they are used in an option dropdown.
	end

	def create
		@mission = Mission.new(mission_params)
		# passes the mission params defined below onto a new instance of Mission
		if logged_in_ty?
			# If a tycoon is logged in continue.
			if @mission.origin != @mission.destination
				# if the missions origin does not equal the destination continue.
				if @mission.save
					# If all the other validations are passed the mission will save and you will be redirected to the mission show page..
					flash[:notice] = "Your mission was saved"
					redirect_to mission_path(@mission.id)
				else
					flash[:notice] = "Your mission was not saved"
					redirect_to :back
					# If not saved it will be redirected back.
				end
			else
				# if origin and destination are the same it will redirect back and flash a notice.
				flash[:notice] = "Your mission was not saved"
				redirect_to :back
			end
		else
			# If user is not a tycoon it will redirect back.
			redirect_to :back
			flash[:notice] = "Must be logged in as a Tycoon to create a Mission!"
		end	
	end

	def show
		# mission variable is equal to the mission for the current show page.
		@mission = Mission.find(params[:id])
		@smuggler_id = @mission.smuggler_id
	end

	def edit
		@mission = Mission.find(params[:id])
		# makes the variable equal to the id equal to the current id page. Same for the update action.
	end

	def update
		@mission = Mission.find(params[:id])
	end

	def destroy
		# making sure that the user is a tycoon and they can cancel the mission.
		if logged_in_ty?
			@mission = Mission.find(params[:id])
			@mission.destroy
			redirect_to missions_path
			# redirect to the missions index.
		else
			redirect_to :back
			flash[:notice] = "You must be a Tycoon to cancel a mission."
			# if not logged in as tycoon it alerts the user and does not cancel and redirects back.
		end
	end

	layout 'mission'
	# use the mission layout for all actions and views related to mission.
	private

	def mission_params
		# defining strong params to pass through.
	params.require(:mission).permit(:cost, :cargo, :origin, :destination, :name, :vehicle_id, :smuggler_id)
	end

end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/views/missions/index.html.erb
<h1>Mission List</h1>
<% @missions.each do |m| %>
	<%= link_to(m.name, mission_path(m.id), method: :get, class: 'mission_index') %>
	<br>

	<% end %>

app/views/missions/new.html.erb
<h1>Create a Mission</h1>
<%= form_for @mission do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :cargo %>
	<%= f.text_field :cargo, size: "60x40" %>
	<%= f.label :cost %>
	<%= f.number_field :cost, min: 1000, step: 1 %>
	<%= f.label :containers %>
	<%= f.number_field :containers, step: 1 %>
	<% v_options = options_from_collection_for_select(@vehicles, 'id', 'name') %>
	<%= f.select :vehicle_id,  v_options %>
	<% s_options = options_from_collection_for_select(@smugglers, 'id', 'username') %>
	<%= f.select :smuggler_id,  s_options %>
	<%= f.label :origin %>
	<%= f.select :origin, [['Philadelphia', 'philadelphia'], ['Atlantic City', 'atlantic city'], ['Chicago', 'chicago'], ['New York', 'new york'], ['Brookyln', 'brooklyn'], ['New Orleans', 'new orleans'], ['Gary', 'gary']] %>
	<%= f.label :destination %>
	<%= f.select :destination, [['Philadelphia', 'philadelphia'], ['Atlantic City', 'atlantic city'], ['Chicago', 'chicago'], ['New York', 'new york'], ['Brookyln', 'brooklyn'], ['New Orleans', 'new orleans'], ['Gary', 'gary']] %>
	<%= f.submit :create %>
	<% end %>

app/views/missions/show.html.erb
<%= content_tag :h1, "Classified", class: "classified" %>

<%= content_tag :p, "name: #{@mission.name}" %>

<%= content_tag :p, "cost: $#{@mission.cost}" %>
<%= content_tag :p, "origin:#{@mission.origin}" %>
<%= content_tag :p, "destination: #{@mission.destination}"%>
<%= content_tag :p, "cargo: #{@mission.cargo}" %>
<%= content_tag :p, "containers #{@mission.containers}" %>
<%= link_to "Vehicle Used: #{@mission.vehicle.name}", vehicle_path(@mission.vehicle.id), method: :get, class: "smuggler_name" %>
<%= image_tag @mission.vehicle.image.url(:medium) %>
<br>
<%= link_to "Smuggler: #{@mission.smuggler.username}", smuggler_path(@mission.smuggler.id), method: :get, class: "smuggler_name" %>
<br>
<%= image_tag @mission.smuggler.avatar.url(:medium) %>
<%= content_tag :p, "Date: #{@mission.created_at}" %>
<% if logged_in_ty? %>
<%= link_to "Cancel Mission", mission_path(@mission), method: :delete, class: "smuggler_name" %>
<% end %>